# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_ordergoods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='axf_cart',
        ),
        migrations.AlterModelTable(
            name='order',
            table='axf_order',
        ),
        migrations.AlterModelTable(
            name='ordergoods',
            table='axf_ordergoods',
        ),
    ]
